services:
  xray-core:
    image: ghcr.io/xtls/xray-core:25.5.16@sha256:be505df0b9a8602a09d54f87a4f8e57153262f44b4ce93d84dcab8bb9adac841
    ports: 
      - "443:443"
    container_name: xray-core
    volumes:
      - type: bind
        source: /etc/xray/xray.json
        target: /etc/xray/xray.json
        read_only: true 
    restart: always
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "xray", "-test", "-format", "json", "-config", "/etc/xray/xray.json"]
