services:
  xray-core:
    image: ghcr.io/xtls/xray-core:25.4.30@sha256:1f2e4629c217aa5f0ae35f144a838f5ad19ca5be0bd850f9eaad12771763487c
    ports: 
      - "443:443"
    container_name: xray-core
    volumes:
      - type: bind
        source: /etc/xray/xray.json
        target: /etc/xray/xray.json
        read_only: true 
    restart: always
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "xray", "-test", "-format", "json", "-config", "/etc/xray/xray.json"]
