services:
  xray-core:
    image: ghcr.io/xtls/xray-core:26.7.11@sha256:a1644183accdb0b5be967093fe34be756fd5de15fe2ee0206e842ae17350967f
    ports: 
      - "443:443"
    container_name: xray-core
    volumes:
      - type: bind
        source: /etc/xray/xray.json
        target: /usr/local/etc/xray/xray.json
        read_only: true 
    restart: always
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "xray", "-test", "-format", "json", "-config", "/usr/local/etc/xray/xray.json"]
