services:
  xray-core:
    image: ghcr.io/xtls/xray-core:26.2.6@sha256:c6daec5244a2110490ec2049d4c6588cbef544a8bcb4b32c5e4da16e15b7f98e
    ports: 
      - "443:443"
    container_name: xray-core
    volumes:
      - type: bind
        source: /etc/xray/xray.json
        target: /usr/local/etc/xray/xray.json
        read_only: true 
    restart: always
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "xray", "-test", "-format", "json", "-config", "/usr/local/etc/xray/xray.json"]
