services:
  xray-core:
    image: ghcr.io/xtls/xray-core:25.9.5@sha256:f0c2a6e6afa6b01dc1057917ce18ec7f0b6ae9a15af3976382aa89c109d6592d
    ports: 
      - "443:443"
    container_name: xray-core
    volumes:
      - type: bind
        source: /etc/xray/xray.json
        target: /usr/local/etc/xray/xray.json
        read_only: true 
    restart: always
    environment:
      - TZ=Europe/Moscow
    healthcheck:
      test: ["CMD", "xray", "-test", "-format", "json", "-config", "/usr/local/etc/xray/xray.json"]
